// <auto-generated />
using Arrive.BusApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arrive.BusApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430224314_AddMetroStations")]
    partial class AddMetroStations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arrive.BusApi.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "80"
                        },
                        new
                        {
                            Id = 2,
                            Number = "90"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("BusRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            RouteName = "خط 80 - مساكن اسكو إلى مستشفى الدمرداش"
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            RouteName = "خط 90 - مساكن اسكو إلى ميدان الجيزة"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.MetroStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetroStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 29.8489,
                            Longitude = 31.334199999999999,
                            Name = "Helwan"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 29.9602,
                            Longitude = 31.2576,
                            Name = "Maadi"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 30.0444,
                            Longitude = 31.235800000000001,
                            Name = "Sadat"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 30.0535,
                            Longitude = 31.238700000000001,
                            Name = "Nasser"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 30.061,
                            Longitude = 31.245999999999999,
                            Name = "Al Shohadaa"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 30.052299999999999,
                            Longitude = 31.2468,
                            Name = "Attaba"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 30.026,
                            Longitude = 31.2013,
                            Name = "Cairo University"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 30.038499999999999,
                            Longitude = 31.2121,
                            Name = "Dokki"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 30.041899999999998,
                            Longitude = 31.224900000000002,
                            Name = "Opera"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 30.073499999999999,
                            Longitude = 31.283100000000001,
                            Name = "Abbassia"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 30.101500000000001,
                            Longitude = 31.333100000000002,
                            Name = "Haroun"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 30.152100000000001,
                            Longitude = 31.3384,
                            Name = "El Marg"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.RouteStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusRouteId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StationOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("BusRouteId", "StationId")
                        .IsUnique();

                    b.HasIndex("BusRouteId", "StationOrder")
                        .IsUnique();

                    b.ToTable("RouteStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusRouteId = 1,
                            StationId = 1,
                            StationOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            BusRouteId = 1,
                            StationId = 2,
                            StationOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            BusRouteId = 1,
                            StationId = 3,
                            StationOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            BusRouteId = 1,
                            StationId = 4,
                            StationOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            BusRouteId = 1,
                            StationId = 5,
                            StationOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            BusRouteId = 1,
                            StationId = 6,
                            StationOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            BusRouteId = 1,
                            StationId = 7,
                            StationOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            BusRouteId = 1,
                            StationId = 8,
                            StationOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            BusRouteId = 1,
                            StationId = 9,
                            StationOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            BusRouteId = 1,
                            StationId = 10,
                            StationOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            BusRouteId = 1,
                            StationId = 11,
                            StationOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            BusRouteId = 1,
                            StationId = 12,
                            StationOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            BusRouteId = 1,
                            StationId = 13,
                            StationOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            BusRouteId = 1,
                            StationId = 14,
                            StationOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            BusRouteId = 1,
                            StationId = 15,
                            StationOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            BusRouteId = 1,
                            StationId = 16,
                            StationOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            BusRouteId = 2,
                            StationId = 1,
                            StationOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            BusRouteId = 2,
                            StationId = 2,
                            StationOrder = 2
                        },
                        new
                        {
                            Id = 19,
                            BusRouteId = 2,
                            StationId = 17,
                            StationOrder = 3
                        },
                        new
                        {
                            Id = 20,
                            BusRouteId = 2,
                            StationId = 4,
                            StationOrder = 4
                        },
                        new
                        {
                            Id = 21,
                            BusRouteId = 2,
                            StationId = 5,
                            StationOrder = 5
                        },
                        new
                        {
                            Id = 22,
                            BusRouteId = 2,
                            StationId = 9,
                            StationOrder = 6
                        },
                        new
                        {
                            Id = 23,
                            BusRouteId = 2,
                            StationId = 18,
                            StationOrder = 7
                        },
                        new
                        {
                            Id = 24,
                            BusRouteId = 2,
                            StationId = 19,
                            StationOrder = 8
                        },
                        new
                        {
                            Id = 25,
                            BusRouteId = 2,
                            StationId = 20,
                            StationOrder = 9
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 30.136900000000001,
                            Longitude = 31.3217,
                            Name = "مساكن اسكو"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 30.140699999999999,
                            Longitude = 31.296800000000001,
                            Name = "بهتيم"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 30.129799999999999,
                            Longitude = 31.3095,
                            Name = "الشارع الجديد"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 30.1389,
                            Longitude = 31.293500000000002,
                            Name = "مسطرد"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 30.117100000000001,
                            Longitude = 31.313099999999999,
                            Name = "المطرية"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 30.095700000000001,
                            Longitude = 31.287600000000001,
                            Name = "الحلمية"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 30.0867,
                            Longitude = 31.307500000000001,
                            Name = "التجنيد"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 30.084099999999999,
                            Longitude = 31.3032,
                            Name = "محكمة"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 30.091100000000001,
                            Longitude = 31.319700000000001,
                            Name = "روكسي"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 30.089099999999998,
                            Longitude = 31.342099999999999,
                            Name = "ارض الجولف"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 30.079699999999999,
                            Longitude = 31.298200000000001,
                            Name = "الخليفة المأمون"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 30.0871,
                            Longitude = 31.294599999999999,
                            Name = "كوبري القبة"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 30.086400000000001,
                            Longitude = 31.284099999999999,
                            Name = "حدائق القبة"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 30.081900000000001,
                            Longitude = 31.278199999999998,
                            Name = "حمامات القبة"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 30.075399999999998,
                            Longitude = 31.274899999999999,
                            Name = "منشية الصدر"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 30.070699999999999,
                            Longitude = 31.271699999999999,
                            Name = "مستشفى الدمرداش"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 30.1327,
                            Longitude = 31.300899999999999,
                            Name = "عرب"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 30.061399999999999,
                            Longitude = 31.245799999999999,
                            Name = "مستشفى الجلاء"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 30.061900000000001,
                            Longitude = 31.246500000000001,
                            Name = "شارع رمسيس"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 30.0106,
                            Longitude = 31.208600000000001,
                            Name = "ميدان الجيزة"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.BusRoute", b =>
                {
                    b.HasOne("Arrive.BusApi.Models.Bus", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.RouteStation", b =>
                {
                    b.HasOne("Arrive.BusApi.Models.BusRoute", "BusRoute")
                        .WithMany("RouteStations")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arrive.BusApi.Models.Station", "Station")
                        .WithMany("RouteStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.Bus", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.BusRoute", b =>
                {
                    b.Navigation("RouteStations");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.Station", b =>
                {
                    b.Navigation("RouteStations");
                });
#pragma warning restore 612, 618
        }
    }
}
