// <auto-generated />
using Arrive.BusApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arrive.BusApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501003013_AddMwasalatMisr")]
    partial class AddMwasalatMisr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arrive.BusApi.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = "80"
                        },
                        new
                        {
                            Id = 2,
                            Number = "90"
                        },
                        new
                        {
                            Id = 3,
                            Number = "M1"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("BusRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            RouteName = "خط 80 - مساكن اسكو إلى مستشفى الدمرداش"
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            RouteName = "خط 90 - مساكن اسكو إلى ميدان الجيزة"
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            RouteName = "خط M1 مواصلات مصر - جامعة القاهرة إلى AUC"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.MetroStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetroStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 29.8491,
                            Longitude = 31.334099999999999,
                            Name = "Helwan"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 29.864100000000001,
                            Longitude = 31.3323,
                            Name = "Ain Helwan"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 29.8706,
                            Longitude = 31.328299999999999,
                            Name = "Helwan University"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 29.882100000000001,
                            Longitude = 31.3218,
                            Name = "Wadi Hof"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 29.897200000000002,
                            Longitude = 31.312899999999999,
                            Name = "Hadayek Helwan"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 29.907900000000001,
                            Longitude = 31.303899999999999,
                            Name = "El-Maasara"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 29.924800000000001,
                            Longitude = 31.291699999999999,
                            Name = "Tora El-Asmant"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 29.936599999999999,
                            Longitude = 31.282900000000001,
                            Name = "Kozzika"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 29.9482,
                            Longitude = 31.274999999999999,
                            Name = "Tora El-Balad"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 29.954599999999999,
                            Longitude = 31.265699999999999,
                            Name = "Sakanat El-Maadi"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 29.9602,
                            Longitude = 31.258500000000002,
                            Name = "Maadi"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 29.972100000000001,
                            Longitude = 31.250499999999999,
                            Name = "Hadayek El-Maadi"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 29.982199999999999,
                            Longitude = 31.242999999999999,
                            Name = "Dar El-Salam"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 29.995899999999999,
                            Longitude = 31.233499999999999,
                            Name = "El-Zahraa"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 30.0062,
                            Longitude = 31.23,
                            Name = "Mar Girgis"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 30.017499999999998,
                            Longitude = 31.229099999999999,
                            Name = "El-Malek El-Saleh"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 30.029599999999999,
                            Longitude = 31.2332,
                            Name = "Al-Sayeda Zeinab"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 30.035699999999999,
                            Longitude = 31.236599999999999,
                            Name = "Saad Zaghloul"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 30.0444,
                            Longitude = 31.235800000000001,
                            Name = "Sadat"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 30.0535,
                            Longitude = 31.238700000000001,
                            Name = "Nasser"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 30.0579,
                            Longitude = 31.242699999999999,
                            Name = "Orabi"
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 30.061,
                            Longitude = 31.245999999999999,
                            Name = "Al-Shohadaa"
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 30.066400000000002,
                            Longitude = 31.264399999999998,
                            Name = "Ghamra"
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 30.0715,
                            Longitude = 31.2727,
                            Name = "El-Demerdash"
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 30.075900000000001,
                            Longitude = 31.276599999999998,
                            Name = "Manshiet El-Sadr"
                        },
                        new
                        {
                            Id = 26,
                            Latitude = 30.081800000000001,
                            Longitude = 31.284500000000001,
                            Name = "Kobri El-Qobba"
                        },
                        new
                        {
                            Id = 27,
                            Latitude = 30.0854,
                            Longitude = 31.290500000000002,
                            Name = "Hammamat El-Qobba"
                        },
                        new
                        {
                            Id = 28,
                            Latitude = 30.0898,
                            Longitude = 31.296500000000002,
                            Name = "Saray El-Qobba"
                        },
                        new
                        {
                            Id = 29,
                            Latitude = 30.098800000000001,
                            Longitude = 31.306899999999999,
                            Name = "Hadayek El-Zaitoun"
                        },
                        new
                        {
                            Id = 30,
                            Latitude = 30.104399999999998,
                            Longitude = 31.3125,
                            Name = "Helmeyet El-Zaitoun"
                        },
                        new
                        {
                            Id = 31,
                            Latitude = 30.114699999999999,
                            Longitude = 31.318100000000001,
                            Name = "El-Matareyya"
                        },
                        new
                        {
                            Id = 32,
                            Latitude = 30.124300000000002,
                            Longitude = 31.323499999999999,
                            Name = "Ain Shams"
                        },
                        new
                        {
                            Id = 33,
                            Latitude = 30.1387,
                            Longitude = 31.328299999999999,
                            Name = "Ezbet El-Nakhl"
                        },
                        new
                        {
                            Id = 34,
                            Latitude = 30.152100000000001,
                            Longitude = 31.3384,
                            Name = "El-Marg"
                        },
                        new
                        {
                            Id = 35,
                            Latitude = 30.1633,
                            Longitude = 31.336400000000001,
                            Name = "New El-Marg"
                        },
                        new
                        {
                            Id = 36,
                            Latitude = 29.980599999999999,
                            Longitude = 31.211400000000001,
                            Name = "El-Mounib"
                        },
                        new
                        {
                            Id = 37,
                            Latitude = 29.995799999999999,
                            Longitude = 31.209800000000001,
                            Name = "Sakiat Mekki"
                        },
                        new
                        {
                            Id = 38,
                            Latitude = 30.005099999999999,
                            Longitude = 31.2089,
                            Name = "Omm El-Misryeen"
                        },
                        new
                        {
                            Id = 39,
                            Latitude = 30.0137,
                            Longitude = 31.207899999999999,
                            Name = "Giza"
                        },
                        new
                        {
                            Id = 40,
                            Latitude = 30.021000000000001,
                            Longitude = 31.204499999999999,
                            Name = "Faisal"
                        },
                        new
                        {
                            Id = 41,
                            Latitude = 30.026,
                            Longitude = 31.2013,
                            Name = "Cairo University"
                        },
                        new
                        {
                            Id = 42,
                            Latitude = 30.035499999999999,
                            Longitude = 31.200099999999999,
                            Name = "El-Bohouth"
                        },
                        new
                        {
                            Id = 43,
                            Latitude = 30.038499999999999,
                            Longitude = 31.2121,
                            Name = "Dokki"
                        },
                        new
                        {
                            Id = 44,
                            Latitude = 30.041899999999998,
                            Longitude = 31.224900000000002,
                            Name = "Opera"
                        },
                        new
                        {
                            Id = 45,
                            Latitude = 30.0443,
                            Longitude = 31.244299999999999,
                            Name = "Mohamed Naguib"
                        },
                        new
                        {
                            Id = 46,
                            Latitude = 30.052299999999999,
                            Longitude = 31.2468,
                            Name = "Attaba"
                        },
                        new
                        {
                            Id = 47,
                            Latitude = 30.070900000000002,
                            Longitude = 31.245200000000001,
                            Name = "Massara"
                        },
                        new
                        {
                            Id = 48,
                            Latitude = 30.081399999999999,
                            Longitude = 31.246400000000001,
                            Name = "Rod El-Farag"
                        },
                        new
                        {
                            Id = 49,
                            Latitude = 30.091000000000001,
                            Longitude = 31.2469,
                            Name = "St. Teresa"
                        },
                        new
                        {
                            Id = 50,
                            Latitude = 30.100899999999999,
                            Longitude = 31.247499999999999,
                            Name = "Khalafawy"
                        },
                        new
                        {
                            Id = 51,
                            Latitude = 30.106999999999999,
                            Longitude = 31.249199999999998,
                            Name = "Mezallat"
                        },
                        new
                        {
                            Id = 52,
                            Latitude = 30.113299999999999,
                            Longitude = 31.2486,
                            Name = "Kolleyyet El-Zeraa"
                        },
                        new
                        {
                            Id = 53,
                            Latitude = 30.122499999999999,
                            Longitude = 31.244700000000002,
                            Name = "Shubra El-Kheima"
                        },
                        new
                        {
                            Id = 54,
                            Latitude = 30.1465,
                            Longitude = 31.421700000000001,
                            Name = "Adly Mansour"
                        },
                        new
                        {
                            Id = 55,
                            Latitude = 30.135999999999999,
                            Longitude = 31.4055,
                            Name = "El Hayestep"
                        },
                        new
                        {
                            Id = 56,
                            Latitude = 30.130199999999999,
                            Longitude = 31.3855,
                            Name = "Omar Ibn El-Khattab"
                        },
                        new
                        {
                            Id = 57,
                            Latitude = 30.1265,
                            Longitude = 31.3705,
                            Name = "Qobaa"
                        },
                        new
                        {
                            Id = 58,
                            Latitude = 30.122499999999999,
                            Longitude = 31.355499999999999,
                            Name = "Hesham Barakat"
                        },
                        new
                        {
                            Id = 59,
                            Latitude = 30.118500000000001,
                            Longitude = 31.345500000000001,
                            Name = "El-Nozha"
                        },
                        new
                        {
                            Id = 60,
                            Latitude = 30.1145,
                            Longitude = 31.3355,
                            Name = "Nadi El-Shams"
                        },
                        new
                        {
                            Id = 61,
                            Latitude = 30.109500000000001,
                            Longitude = 31.325500000000002,
                            Name = "Alf Maskan"
                        },
                        new
                        {
                            Id = 62,
                            Latitude = 30.1005,
                            Longitude = 31.320499999999999,
                            Name = "Heliopolis Square"
                        },
                        new
                        {
                            Id = 63,
                            Latitude = 30.093499999999999,
                            Longitude = 31.3155,
                            Name = "Haroun"
                        },
                        new
                        {
                            Id = 64,
                            Latitude = 30.0885,
                            Longitude = 31.3125,
                            Name = "Al-Ahram"
                        },
                        new
                        {
                            Id = 65,
                            Latitude = 30.083500000000001,
                            Longitude = 31.3095,
                            Name = "Koleyet El-Banat"
                        },
                        new
                        {
                            Id = 66,
                            Latitude = 30.073499999999999,
                            Longitude = 31.3065,
                            Name = "Stadium"
                        },
                        new
                        {
                            Id = 67,
                            Latitude = 30.070499999999999,
                            Longitude = 31.298500000000001,
                            Name = "Fair Zone"
                        },
                        new
                        {
                            Id = 68,
                            Latitude = 30.073499999999999,
                            Longitude = 31.283100000000001,
                            Name = "Abbassia"
                        },
                        new
                        {
                            Id = 69,
                            Latitude = 30.0655,
                            Longitude = 31.275500000000001,
                            Name = "Abdo Pasha"
                        },
                        new
                        {
                            Id = 70,
                            Latitude = 30.060500000000001,
                            Longitude = 31.265499999999999,
                            Name = "El-Geish"
                        },
                        new
                        {
                            Id = 71,
                            Latitude = 30.055499999999999,
                            Longitude = 31.255500000000001,
                            Name = "Bab El-Shaaria"
                        },
                        new
                        {
                            Id = 72,
                            Latitude = 30.055099999999999,
                            Longitude = 31.232500000000002,
                            Name = "Maspero"
                        },
                        new
                        {
                            Id = 73,
                            Latitude = 30.0625,
                            Longitude = 31.2225,
                            Name = "Safaa Hegazy"
                        },
                        new
                        {
                            Id = 74,
                            Latitude = 30.0685,
                            Longitude = 31.212499999999999,
                            Name = "Kit Kat"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.RouteStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusRouteId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("StationOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("BusRouteId", "StationId")
                        .IsUnique();

                    b.HasIndex("BusRouteId", "StationOrder")
                        .IsUnique();

                    b.ToTable("RouteStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusRouteId = 1,
                            StationId = 1,
                            StationOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            BusRouteId = 1,
                            StationId = 2,
                            StationOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            BusRouteId = 1,
                            StationId = 3,
                            StationOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            BusRouteId = 1,
                            StationId = 4,
                            StationOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            BusRouteId = 1,
                            StationId = 5,
                            StationOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            BusRouteId = 1,
                            StationId = 6,
                            StationOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            BusRouteId = 1,
                            StationId = 7,
                            StationOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            BusRouteId = 1,
                            StationId = 8,
                            StationOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            BusRouteId = 1,
                            StationId = 9,
                            StationOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            BusRouteId = 1,
                            StationId = 10,
                            StationOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            BusRouteId = 1,
                            StationId = 11,
                            StationOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            BusRouteId = 1,
                            StationId = 12,
                            StationOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            BusRouteId = 1,
                            StationId = 13,
                            StationOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            BusRouteId = 1,
                            StationId = 14,
                            StationOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            BusRouteId = 1,
                            StationId = 15,
                            StationOrder = 15
                        },
                        new
                        {
                            Id = 17,
                            BusRouteId = 2,
                            StationId = 1,
                            StationOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            BusRouteId = 2,
                            StationId = 2,
                            StationOrder = 2
                        },
                        new
                        {
                            Id = 19,
                            BusRouteId = 2,
                            StationId = 17,
                            StationOrder = 3
                        },
                        new
                        {
                            Id = 20,
                            BusRouteId = 2,
                            StationId = 4,
                            StationOrder = 4
                        },
                        new
                        {
                            Id = 21,
                            BusRouteId = 2,
                            StationId = 5,
                            StationOrder = 5
                        },
                        new
                        {
                            Id = 22,
                            BusRouteId = 2,
                            StationId = 9,
                            StationOrder = 6
                        },
                        new
                        {
                            Id = 23,
                            BusRouteId = 2,
                            StationId = 18,
                            StationOrder = 7
                        },
                        new
                        {
                            Id = 24,
                            BusRouteId = 2,
                            StationId = 19,
                            StationOrder = 8
                        },
                        new
                        {
                            Id = 25,
                            BusRouteId = 2,
                            StationId = 20,
                            StationOrder = 9
                        },
                        new
                        {
                            Id = 26,
                            BusRouteId = 3,
                            StationId = 21,
                            StationOrder = 1
                        },
                        new
                        {
                            Id = 27,
                            BusRouteId = 3,
                            StationId = 22,
                            StationOrder = 2
                        },
                        new
                        {
                            Id = 28,
                            BusRouteId = 3,
                            StationId = 23,
                            StationOrder = 3
                        },
                        new
                        {
                            Id = 29,
                            BusRouteId = 3,
                            StationId = 24,
                            StationOrder = 4
                        },
                        new
                        {
                            Id = 30,
                            BusRouteId = 3,
                            StationId = 25,
                            StationOrder = 5
                        },
                        new
                        {
                            Id = 31,
                            BusRouteId = 3,
                            StationId = 26,
                            StationOrder = 6
                        },
                        new
                        {
                            Id = 32,
                            BusRouteId = 3,
                            StationId = 27,
                            StationOrder = 7
                        },
                        new
                        {
                            Id = 33,
                            BusRouteId = 3,
                            StationId = 28,
                            StationOrder = 8
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 30.136900000000001,
                            Longitude = 31.3217,
                            Name = "مساكن اسكو"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 30.140699999999999,
                            Longitude = 31.296800000000001,
                            Name = "بهتيم"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 30.129799999999999,
                            Longitude = 31.3095,
                            Name = "الشارع الجديد"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 30.1389,
                            Longitude = 31.293500000000002,
                            Name = "مسطرد"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 30.117100000000001,
                            Longitude = 31.313099999999999,
                            Name = "المطرية"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 30.095700000000001,
                            Longitude = 31.287600000000001,
                            Name = "الحلمية"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 30.0867,
                            Longitude = 31.307500000000001,
                            Name = "التجنيد"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 30.084099999999999,
                            Longitude = 31.3032,
                            Name = "محكمة"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 30.091100000000001,
                            Longitude = 31.319700000000001,
                            Name = "روكسي"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 30.089099999999998,
                            Longitude = 31.342099999999999,
                            Name = "ارض الجولف"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 30.079699999999999,
                            Longitude = 31.298200000000001,
                            Name = "الخليفة المأمون"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 30.0871,
                            Longitude = 31.294599999999999,
                            Name = "كوبري القبة"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 30.086400000000001,
                            Longitude = 31.284099999999999,
                            Name = "حدائق القبة"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 30.081900000000001,
                            Longitude = 31.278199999999998,
                            Name = "حمامات القبة"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 30.075399999999998,
                            Longitude = 31.274899999999999,
                            Name = "منشية الصدر"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 30.070699999999999,
                            Longitude = 31.271699999999999,
                            Name = "مستشفى الدمرداش"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 30.1327,
                            Longitude = 31.300899999999999,
                            Name = "عرب"
                        },
                        new
                        {
                            Id = 18,
                            Latitude = 30.061399999999999,
                            Longitude = 31.245799999999999,
                            Name = "مستشفى الجلاء"
                        },
                        new
                        {
                            Id = 19,
                            Latitude = 30.061900000000001,
                            Longitude = 31.246500000000001,
                            Name = "شارع رمسيس"
                        },
                        new
                        {
                            Id = 20,
                            Latitude = 30.0106,
                            Longitude = 31.208600000000001,
                            Name = "ميدان الجيزة"
                        },
                        new
                        {
                            Id = 21,
                            Latitude = 30.026,
                            Longitude = 31.2013,
                            Name = "جامعة القاهرة"
                        },
                        new
                        {
                            Id = 22,
                            Latitude = 30.038399999999999,
                            Longitude = 31.212299999999999,
                            Name = "ميدان الدقي"
                        },
                        new
                        {
                            Id = 23,
                            Latitude = 30.0444,
                            Longitude = 31.235700000000001,
                            Name = "ميدان التحرير"
                        },
                        new
                        {
                            Id = 24,
                            Latitude = 30.063400000000001,
                            Longitude = 31.247199999999999,
                            Name = "ميدان رمسيس"
                        },
                        new
                        {
                            Id = 25,
                            Latitude = 30.0718,
                            Longitude = 31.282900000000001,
                            Name = "العباسية"
                        },
                        new
                        {
                            Id = 26,
                            Latitude = 30.057099999999998,
                            Longitude = 31.341100000000001,
                            Name = "مكرم عبيد (مدينة نصر)"
                        },
                        new
                        {
                            Id = 27,
                            Latitude = 30.0335,
                            Longitude = 31.455500000000001,
                            Name = "الووتر واي (التجمع)"
                        },
                        new
                        {
                            Id = 28,
                            Latitude = 30.016300000000001,
                            Longitude = 31.5032,
                            Name = "الجامعة الأمريكية (AUC)"
                        });
                });

            modelBuilder.Entity("Arrive.BusApi.Models.BusRoute", b =>
                {
                    b.HasOne("Arrive.BusApi.Models.Bus", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.RouteStation", b =>
                {
                    b.HasOne("Arrive.BusApi.Models.BusRoute", "BusRoute")
                        .WithMany("RouteStations")
                        .HasForeignKey("BusRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arrive.BusApi.Models.Station", "Station")
                        .WithMany("RouteStations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusRoute");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.Bus", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.BusRoute", b =>
                {
                    b.Navigation("RouteStations");
                });

            modelBuilder.Entity("Arrive.BusApi.Models.Station", b =>
                {
                    b.Navigation("RouteStations");
                });
#pragma warning restore 612, 618
        }
    }
}
